# Generated by Django 4.2.7 on 2026-02-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='assigned_events',
            field=models.ManyToManyField(blank=True, related_name='assigned_staff', to='tickets.event'),
        ),
    ]
