# Generated by Django 4.2.7 on 2026-02-28 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_staffprofile_assigned_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(editable=False, max_length=10)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.AddField(
            model_name='subevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_events', to='tickets.event'),
        ),
        migrations.AlterUniqueTogether(
            name='entrytype',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='entrytype',
            name='sub_event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entry_types', to='tickets.subevent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='sub_event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.subevent'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['sub_event', 'created_at'], name='tickets_tic_sub_eve_6e33a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='entrytype',
            unique_together={('sub_event', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='subevent',
            unique_together={('event', 'code')},
        ),
        migrations.RemoveField(
            model_name='entrytype',
            name='event',
        ),
    ]
