# Generated by Django 4.2.7 on 2026-02-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_subevent_ticket_tickets_tic_sub_eve_6e33a8_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='assigned_events',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='assigned_sub_events',
            field=models.ManyToManyField(blank=True, related_name='assigned_staff', to='tickets.subevent'),
        ),
    ]
