# Generated by Django 4.2.7 on 2026-03-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_remove_staffprofile_assigned_events_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='group_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='quantity_in_group',
            field=models.IntegerField(default=1),
        ),
    ]
