# Generated by Django 4.2.7 on 2026-03-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_group_id_ticket_quantity_in_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubEventMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sub Event Master',
                'verbose_name_plural': 'Sub Event Masters',
                'ordering': ['name'],
            },
        ),
    ]
