# Generated by Django 4.2.7 on 2026-03-18 07:08

from django.db import migrations


def populate_master_sub_events(apps, schema_editor):
    """Populate SubEventMaster with initial predefined sub-events"""
    SubEventMaster = apps.get_model('tickets', 'SubEventMaster')
    
    initial_sub_events = [
        'ENTRY TICKET',
        'Giant wheel',
        'Break dance',
        'Colombus',
        'Well of death',
        'Ranger',
        'Dragon train',
        'Bouncy',
        'Toy car',
        'Toy helicopter',
        'Toy Boat'
    ]
    
    for name in initial_sub_events:
        SubEventMaster.objects.get_or_create(
            name=name,
            defaults={
                'description': f'Predefined sub-event: {name}',
                'is_active': True
            }
        )


def reverse_populate_master_sub_events(apps, schema_editor):
    """Remove all SubEventMaster entries"""
    SubEventMaster = apps.get_model('tickets', 'SubEventMaster')
    SubEventMaster.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_subeventmaster'),
    ]

    operations = [
        migrations.RunPython(
            populate_master_sub_events,
            reverse_populate_master_sub_events
        ),
    ]